# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextInputPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('regexp', models.TextField()),
                ('type', models.IntegerField(choices=[(0, b'To Do'), (1, b'In Progress'), (2, b'Done')], default=2)),
                ('power', models.IntegerField(choices=[(1, b'Very Low'), (2, b'Low'), (3, b'Medium'), (4, b'High'), (5, b'Very High')], default=3)),
            ],
        ),
    ]
