# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import teofibotweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('power', models.IntegerField(choices=[(1, b'Very Low'), (2, b'Low'), (3, b'Medium'), (4, b'High'), (5, b'Very High')], default=3)),
                ('message', models.TextField(blank=True, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('sticker', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='NOT LABELED', max_length=200)),
                ('type', models.CharField(choices=[(b'sounds', b'Audio File'), (b'pics', b'Picture'), (b'smileys', b'Smiley Picture'), (b'documents', b'Documents, GIFs, ANY FILE')], max_length=200)),
                ('file', models.FileField(upload_to=teofibotweb.models.resource_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='NOT LABELED', max_length=200)),
                ('file_id', models.CharField(max_length=200, unique=True)),
                ('file_path', models.CharField(max_length=200)),
                ('is_cool', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='publication date')),
            ],
        ),
        migrations.CreateModel(
            name='StickerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='NOT LABELED', max_length=200)),
                ('reply', models.TextField(blank=True, null=True)),
                ('specialReply', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextInputPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('regexp', models.TextField()),
                ('type', models.IntegerField(choices=[(0, b'Negative'), (1, b'Neutral'), (2, b'Positive')], default=2)),
                ('power', models.IntegerField(choices=[(1, b'Very Low'), (2, b'Low'), (3, b'Medium'), (4, b'High'), (5, b'Very High')], default=3)),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teofibotweb.AutoResponse')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='textinputpattern',
            name='senders',
            field=models.ManyToManyField(blank=True, null=True, to='teofibotweb.User'),
        ),
        migrations.AddField(
            model_name='textinputpattern',
            name='specialResponse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialResponse', to='teofibotweb.AutoResponse'),
        ),
        migrations.AddField(
            model_name='stickerresponse',
            name='reply_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='replyTags', to='teofibotweb.Tag'),
        ),
        migrations.AddField(
            model_name='stickerresponse',
            name='stickers',
            field=models.ManyToManyField(blank=True, null=True, related_name='stickers', to='teofibotweb.Sticker'),
        ),
        migrations.AddField(
            model_name='stickerresponse',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='teofibotweb.Tag'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='teofibotweb.Tag'),
        ),
    ]
