# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('power', models.IntegerField(choices=[(1, b'Very Low'), (2, b'Low'), (3, b'Medium'), (4, b'High'), (5, b'Very High')], default=3)),
                ('message', models.TextField(blank=True, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('sticker', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='textinputpattern',
            name='type',
            field=models.IntegerField(choices=[(0, b'Negative'), (1, b'Neutral'), (2, b'Positive')], default=2),
        ),
        migrations.AddField(
            model_name='textinputpattern',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teofibotweb.AutoResponse'),
        ),
    ]
