# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinputpattern',
            name='senders',
            field=models.ManyToManyField(blank=True, null=True, to='teofibotweb.User'),
        ),
    ]
