# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0004_textinputpattern_senders'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinputpattern',
            name='specialResponse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialResponse', to='teofibotweb.AutoResponse'),
        ),
    ]
