# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0010_sticker_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='file_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
