# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0011_sticker_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='specialReply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
