# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0012_auto_20161206_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='reply_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='replyTags', to='teofibotweb.Tag'),
        ),
    ]
