# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0013_sticker_reply_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sticker',
            new_name='StickerResponse',
        ),
    ]
