# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0014_auto_20161206_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='NOT LABELED', max_length=200)),
                ('file_id', models.CharField(max_length=200, unique=True)),
                ('file_path', models.CharField(max_length=200)),
                ('is_cool', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='publication date')),
            ],
        ),
    ]
