# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0015_sticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerresponse',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='stickerresponse',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='stickerresponse',
            name='is_cool',
        ),
        migrations.RemoveField(
            model_name='stickerresponse',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='stickerresponse',
            name='stickers',
            field=models.ManyToManyField(blank=True, null=True, related_name='stickers', to='teofibotweb.Sticker'),
        ),
    ]
