# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0018_autoresponse_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='document',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
