# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import teofibotweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('teofibotweb', '0019_autoresponse_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='NOT LABELED', max_length=200)),
                ('type', models.CharField(choices=[(b'sounds', b'Audio File'), (b'pics', b'Picture'), (b'smileys', b'Smiley Picture'), (b'documents', b'Documents, GIFs, ANY FILE')], max_length=200)),
                ('file', models.FileField(upload_to=teofibotweb.models.resource_directory_path)),
            ],
        ),
    ]
