# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, b'TV'), (2, b'STEREO'), (3, b'AIR CONDITIONER'), (4, b'OTHER')], default=1)),
                ('location', models.IntegerField(choices=[(1, b'LIVING ROOM'), (2, b'DINNING ROOM'), (3, b'BEDROOM'), (4, b'BATHROOM'), (5, b'OTHER')], default=1)),
                ('lirc_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rc_button_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lirc_name', models.CharField(max_length=400)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ircontrol.Device')),
            ],
        ),
    ]
