# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ircontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaction',
            name='layout_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceaction',
            name='layout_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deviceaction',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ircontrol.Device'),
        ),
    ]
