# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircontrol', '0002_auto_20161222_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaction',
            name='button_class',
            field=models.CharField(choices=[(b'btn-info', b'LIGHT BLUE'), (b'btn-primary', b'BLUE'), (b'btn-warning', b'YELLOW'), (b'btn-success', b'GREEN'), (b'btn-danger', b'RED')], default=b'btn-primary', max_length=20),
        ),
    ]
